ASPNETMVC/MVCSampleApp/src/MVCSampleApp/Controllers/TagHelpersController.cs
using Microsoft.AspNetCore.Mvc;
using MVCSampleApp.Models;
using System;
using System.Collections.Generic;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace MVCSampleApp.Controllers
{
    public class TagHelpersController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index() => View();

        public IActionResult LabelHelper() => View(GetSampleMenu());

        public IActionResult InputHelper() => View(GetSampleMenu());

        public IActionResult FormHelper() => View(GetSampleMenu());


        [HttpPost]
        public IActionResult FormHelper(Menu m)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            ViewBag.Status = "Success";
            return View("ValidationHelperResult", m);            
        }

        public IActionResult CustomHelper() => View(GetSampleMenus());

       

        private Menu GetSampleMenu() =>
            new Menu
            {
                Id = 1,
                Text = "Schweinsbraten mit Knödel und Sauerkraut",
                Price = 6.9,
                Date = new DateTime(2016, 10, 5),
                Category = "Main"
            };

        private IList<Menu> GetSampleMenus() =>
            new List<Menu>()
            {
                new Menu
                {
                    Id = 1,
                    Text = "Schweinsbraten mit Knödel und Sauerkraut",
                    Price = 8.5,
                    Date = new DateTime(2016, 10, 5),
                    Category = "Main"
                },
                new Menu
                {
                    Id = 2,
                    Text = "Erdäpfelgulasch mit Tofu und Gebäck",
                    Price = 8.5,
                    Date = new DateTime(2016, 10, 6),
                    Category = "Vegetarian"
                },
                new Menu
                {
                    Id = 3,
                    Text = "Tiroler Bauerngröst'l mit Spiegelei und Krautsalat",
                    Price = 8.5,
                    Date = new DateTime(2016, 10, 7),
                    Category = "Vegetarian"
                }
            };
    }
}

ASPNETMVC/MVCSampleApp/src/MVCSampleApp/Views/TagHelpers/CustomHelper.cshtml
@model IEnumerable<Menu>
@*@addTagHelper "*, MVCSampleApp"*@

<table items="Model" count="Model.Count()" class="sample">

</table>

ASPNETMVC/MVCSampleApp/src/MVCSampleApp/Views/TagHelpers/Display.cshtml
@model MVCSampleApp.Models.Menu
@{
    ViewBag.Title = "Display";
}
<h2>@ViewBag.Title</h2>
@Html.DisplayForModel()

ASPNETMVC/MVCSampleApp/src/MVCSampleApp/Views/TagHelpers/FormHelper.cshtml
@model MVCSampleApp.Models.Menu
@{
    ViewBag.Title = "Form Helper";
}
<h2> @ViewBag.Title</h2>

<form method="post" asp-method="FormHelper">
    <input asp-for="Id" hidden="hidden" />
    <hr />
    
    <label asp-for="Text"></label>
    <div>
        <input asp-for="Text" />
        <span asp-validation-for="Text"></span>
    </div>
    <br />
    <label asp-for="Price"></label>
    <div>
        <input asp-for="Price" />
        <span asp-validation-for="Price"></span>
    </div>
    <br />
    <label asp-for="Date"></label>
    <div>
        <input asp-for="Date" />
        <span asp-validation-for="Date"></span>
    </div>
    <label asp-for="Category"></label>
    <div>
        <input asp-for="Category" />
        <span asp-validation-for="Category"></span>
    </div>
    <input type="submit" value="Submit" />
</form>

ASPNETMVC/MVCSampleApp/src/MVCSampleApp/Views/TagHelpers/FormHelperResult.cshtml
@model MVCSampleApp.Models.Menu
@{
    ViewBag.Title = "Form Helper";
}
<h2> @ViewBag.Title</h2>


<h3>@ViewBag.Status</h3>

ASPNETMVC/MVCSampleApp/src/MVCSampleApp/Views/TagHelpers/HelperList.cshtml
@{
    ViewBag.Title = "Helper List";
}
@model IEnumerable<SelectListItem>
<h2>@ViewBag.Title</h2>
@Html.DropDownList("carslist", Model)

ASPNETMVC/MVCSampleApp/src/MVCSampleApp/Views/TagHelpers/HelperWithMenu.cshtml
@model MVCSampleApp.Models.Menu
@{
    ViewBag.Title = "HelperWithMenu";
}
<h2>Helper with Menu</h2>
@Html.DisplayName("Text:")
@Html.Display("Text")
<br />
@Html.DisplayName("Category:")
@Html.Display("Category")

@Html.TextBox("text1", "input text here",
  new { required = "required", maxlength = 15, @class = "CSSDemo" })

ASPNETMVC/MVCSampleApp/src/MVCSampleApp/Views/TagHelpers/Index.cshtml
@{
    ViewBag.Title = "Anchor Helper";
}
<h2> @ViewBag.Title</h2>

<a asp-controller="Home" asp-action="Index">Home</a>
<br />
<a asp-action="LabelHelper">Label Tag Helper</a>
<br />
<a asp-action="InputTypeHelper">Input Type Tag Helper</a>

ASPNETMVC/MVCSampleApp/src/MVCSampleApp/Views/TagHelpers/Index2.cshtml
@model MVCSampleApp.Models.Menu

@{
    ViewBag.Title = "Tag Helpers";
}
<h2> @ViewBag.Title</h2>

<div class="form-group">
    <label asp-for="Text" class="col-md-2 control-label"></label>
    <div class="col-md-10">
        <input asp-for="Text" class="form-control" />
        <span asp-validation-for="Text" class="text-danger" />
    </div>
    <div class="col-md-10">
        <input asp-for="Price" class="form-control" />
        <span asp-validation-for="Price" class="text-danger" />
    </div>
    <a asp-controller="Home" asp-action="Index">click this</a>
</div>

ASPNETMVC/MVCSampleApp/src/MVCSampleApp/Views/TagHelpers/InputHelper.cshtml
@model MVCSampleApp.Models.Menu
@{
    ViewBag.Title = "Input Helper";
}
<h2> @ViewBag.Title</h2>

<label  asp-for="Text"></label>
<input asp-for="Text"/>
<br/>
<label asp-for="Price"></label>
<input asp-for="Price" />
<br />
<label asp-for="Date"></label>
<input asp-for="Date" />

ASPNETMVC/MVCSampleApp/src/MVCSampleApp/Views/TagHelpers/LabelHelper.cshtml
@model MVCSampleApp.Models.Menu
@{
    ViewBag.Title = "Label Tag Helper";
}
<h2> @ViewBag.Title</h2>

<label asp-for="Text"></label>
<br/>
<label asp-for="Price"></label>
<br />
<label asp-for="Date"></label>

ASPNETMVC/MVCSampleApp/src/MVCSampleApp/Views/TagHelpers/MenuEditor.cshtml
@model MVCSampleApp.Models.Menu
@{
    ViewBag.Title = "HelperWithMenu";
}
<h2> @ViewBag.Title</h2>

@Html.EditorForModel()

ASPNETMVC/MVCSampleApp/src/MVCSampleApp/Views/TagHelpers/SimpleHelper.cshtml
<form asp-controller="TagHelpers" asp-action="SimpleHelper" method="post">
    Check this (or not)
    <input type="checkbox" name="check1" value="true" />
</form>

ASPNETMVC/MVCSampleApp/src/MVCSampleApp/Views/TagHelpers/StronglyTypedMenu.cshtml
@model MVCSampleApp.Models.Menu
@Html.DisplayNameFor(m => m.Text)
<br />
@Html.DisplayFor(m => m.Text)
<br />
@Html.TextBoxFor(m => m.Text)